Small QOL changes mostly for dedicated server owners.
XLabsProject/s1x-client pull request #125
Opened 2021-04-24 22:21 UTC by xerxes-at

* CommandDump and dvarDump now accept a file name as an optional argument to store the output on disk.
    * There might be a bit of performance that could be gained by not opening the file, appending to it and closing it again for every line. But its only run on demand so it should be fine.
* sv_network_fps unlocked.
    * Cheat protection removed.
    * Bumped maximum and default to 1000 times a second.
* Added sv_autoPriority to temporarily lower our process priority while we load a new map to not cause lag spikes on other servers that have their main thread on the same CPU core as we do.
    * This assumes that the dedicated servers are running with a priority above normal as it will lower it to normal during the map rotation.

2021-04-25 09:24 UTC, momo5502 requested changes

2021-04-25 09:24 UTC, momo5502 commented on src/client/component/map_rotation.cpp
> +					}
Looks like that could be extracted into a function

2021-04-25 09:24 UTC, momo5502 commented on src/client/component/command.cpp
> +					}
I see the point of all this, but just as an info: The entire console output can be grabbed using a debug viewer, such as this one: https://docs.microsoft.com/en-us/sysinternals/downloads/debugview

2021-04-25 09:24 UTC, momo5502 commented on src/client/component/command.cpp
> +						if (argument.size() == 2)
would check if(!filename.empty()) here

2021-04-25 09:24 UTC, momo5502 commented on src/client/component/command.cpp
> +							utils::io::write_file(filename, line, i == 0 ? false : true);
Would store all that into a std::string buffer and write it to a file all at once at the end without appending.
Because that way, if you do the command again it will just append again and the file gets longer. Instead of overwriting it

2021-04-25 09:24 UTC, momo5502 commented on src/client/component/command.cpp
> +							utils::io::write_file(filename, line, i == 0 ? false : true);
Same here as above

2021-04-25 13:03 UTC, xerxes-at commented on src/client/component/command.cpp
> +							utils::io::write_file(filename, line, i == 0 ? false : true);
The first line will not be appended to the file but instead cause it to be overwritten. This also works if you overwrite a much larger file.

2021-04-25 13:25 UTC, xerxes-at commented
Applied all but one suggestion of yours as the code already does overwrite the file.

2021-04-25 18:11 UTC, momo5502 approved these changes
Looks good. Will merge it later tho, I will push an update today, probably and I want this to be merged after the update, as it contains complex changes that need a bit of testing

2021-04-28 14:53 UTC, momo5502 approved these changes

2021-04-28 14:53 UTC, merged