Script function support
XLabsProject/s1x-client pull request #183
Opened 2021-05-13 19:13 UTC by fedddddd

2021-05-15 08:30 UTC, momo5502 requested changes

2021-05-15 08:30 UTC, momo5502 commented on src/client/game/scripting/execution.cpp
> +		const auto local_id = game::AllocThread(id);
Don't you have to free the thread again?

2021-05-16 19:54 UTC, momo5502 commented on src/client/game/scripting/execution.cpp
> +		game::RemoveRefToObject(result);
Don't you have to use Scr_FreeThread or something like that? Or is that something different

2021-05-16 20:42 UTC, mjkzy commented on src/client/game/scripting/execution.cpp
> +		game::RemoveRefToObject(result);
if he's hooking/messing with something to do with executing threads (or Scr_ExecThread), then I believe so

2021-05-16 20:45 UTC, fedddddd commented on src/client/game/scripting/execution.cpp
> +		game::RemoveRefToObject(result);
Scr_FreeThead simply calls RemoveRefToObject so it makes no difference

2021-05-17 09:43 UTC, merged

2021-05-17 09:45 UTC, momo5502 commented
I merged it, but still. Can VM_Execute throw exceptions? I think it can. Catching these might maybe be potentially important? Or does it handle all exceptions internally?

2021-05-17 13:08 UTC, fedddddd commented
It handles them internally

2021-05-17 13:50 UTC, momo5502 commented
Perfect