Add listassetpool, fix various problems
XLabsProject/s1x-client pull request #32
Opened 2021-03-11 21:49 UTC by iAmThatMichael

- Fix console display line offset not being reset after calling clear
- Fix opening server menu in a match causing LUI errors to show in console
- Fix LUI crashing whenever calling a map inside a map which was only seen clientside
- Lower the version text display in console to fix text overlapping
- Add listassetpool command replacing the specific pool listing commands

2021-03-12 06:47 UTC, momo5502 requested changes

2021-03-12 06:47 UTC, momo5502 commented on src/client/component/command.cpp
> +
What a murder lambda, pls extract that into smaller functions

2021-03-12 06:47 UTC, momo5502 commented on src/client/component/command.cpp
> +			});
Same here, not gonna review a 200 line function

2021-03-12 06:47 UTC, momo5502 commented on src/client/component/game_console.cpp
> +				return false;
Brackets please:
 if()
 {
 //
}

2021-03-12 06:47 UTC, momo5502 commented on src/client/game/symbols.hpp
> +	WEAK symbol<const char* (const XAsset* asset)> DB_GetXAssetName{ 0x140151C00, 0x140240DD0 };
No spaces within the brackets:
{0x140151C00, 0x140240DD0}

2021-03-12 06:47 UTC, momo5502 commented on src/client/game/symbols.hpp
> +	WEAK symbol<XAssetEntry> g_assetEntryPool{ 0x142CC2400, 0x14379F100 };
same here

2021-03-12 07:04 UTC, momo5502 requested changes
listassetpool lambda is still a fucking bomb, rest is fine tho

2021-03-12 07:04 UTC, momo5502 commented on src/client/component/command.cpp
> +			});
this bro.

2021-03-12 07:38 UTC, iAmThatMichael commented on src/client/component/command.cpp
> +	void list_asset_pool(const game::XAssetType type)
it'd be better if I could move this into fastfiles.cpp would make somewhat more sense there but for now it should be okay in here, commands would require fastfile header which idk if you want to introduce in here

2021-03-12 07:46 UTC, momo5502 commented on src/client/component/command.cpp
> +			table++;
That's still a bomb, but it's ok

2021-03-12 07:46 UTC, momo5502 commented on src/client/component/command.cpp
> +	void list_asset_pool(const game::XAssetType type)
Isn't there DB_EnumXAssets which does exactly that?

2021-03-12 07:54 UTC, iAmThatMichael commented on src/client/component/command.cpp
> +	void list_asset_pool(const game::XAssetType type)
DB_EnumXAssets may be a replacement if it doesn't keep track overridden assets then I wouldn't recommend it, the point of listassetpools is to track where assets are loaded from in each respected fastfile eventually I want to add support for display the zone it's loaded from

2021-03-12 07:58 UTC, momo5502 commented on src/client/component/command.cpp
> +	void list_asset_pool(const game::XAssetType type)
void __cdecl DB_EnumXAssets_Internal(XAssetType type, void (__cdecl *func)(XAssetHeader, void *), void *inData, _BOOL1 includeOverride)

You can choose if you want them or not. Looks like a better solution to me

2021-03-12 08:01 UTC, iAmThatMichael commented on src/client/component/command.cpp
> +	void list_asset_pool(const game::XAssetType type)
I'll double check it in the morning to see if it's viable, I'm pretty sure I tried messing with it but it required the struct data for each asset type, which we don't have.

2021-03-12 08:04 UTC, momo5502 commented on src/client/component/command.cpp
> +	void list_asset_pool(const game::XAssetType type)
I highly doubt it requires that, but yeah, double check it please

2021-03-13 02:36 UTC, iAmThatMichael commented on src/client/component/command.cpp
> +	void list_asset_pool(const game::XAssetType type)
After talking to others it's come to the conclusion we can't get DB_EnumXAssets_Internal to work as the callback parameter is C-style function pointer which doesn't allow a lambda capture which is necessary to know what type is being processed to create the XAsset, this is the only method that's viable for now.

2021-03-13 18:48 UTC, momo5502 approved these changes

2021-03-13 18:48 UTC, merged