fix stats
XLabsProject/s1x-client pull request #346
Opened 2022-03-18 20:18 UTC by skkuull

2022-03-22 05:26 UTC, momo5502 requested changes
How does it fix that?

2022-03-22 05:26 UTC, momo5502 commented on src/client/component/stats.cpp
> -		int is_item_unlocked_stub(void* a1, void* a2, void* a3)
prefer void* if type is unknown.

2022-03-22 15:15 UTC, skkuull commented
> How does it fix that?

when the player set attachments on the weapon, it doesn't apply to the server because the server doesn't have them unlocked
so the player will have no attachments on weapons

the solution was unlocking stuff for dedis which fixed this issue

2022-03-23 12:00 UTC, momo5502 approved these changes

2022-03-23 12:01 UTC, merged