add discord presence
XLabsProject/s1x-client pull request #36
Opened 2021-03-13 15:59 UTC by mjkzy

added discord presence (taken from iw6x open source) and got it working on S1x

current bugs/issues:
- (line 20) trying to get the "Main Menu" state to work in lobby glitches because of VirtualLobby counting as in-game (i think?)
- (line 43) need to get the right address for the host name and uncomment
- (line 38) getting the Localized version of gametype & map does not work but I think im using the right function.
- (line 49) cgArray does not exist on S1x yet or at all. because of this, partySize is not set.
- (line 88) need to change the Discord Client ID for application

2021-03-13 18:51 UTC, momo5502 requested changes
Good job, but the TODOs need to be done ;)

2021-03-13 18:51 UTC, momo5502 commented on src/client/component/discord.cpp
> +			Discord_Initialize("820306675873087529", &handlers, 1, nullptr);
Which ID is that? Did you reserve it? Probably makes sense if it's reserved under the X Labs discord account

2021-03-13 18:51 UTC, momo5502 commented on src/client/component/discord.cpp
> +#endif
Empty line missing

2021-03-13 18:51 UTC, momo5502 commented on src/client/component/discord.cpp
> +				discord_presence.state = "Placeholder";
Not good ;)

2021-03-13 18:51 UTC, momo5502 commented on src/client/component/discord.cpp
> +				/*discord_presence.partySize = game::mp::cgArray->snap != nullptr
ALso needs to be done :D

2021-03-14 01:56 UTC, mjkzy commented on src/client/component/discord.cpp
> +			Discord_Initialize("820306675873087529", &handlers, 1, nullptr);
this is one i made up for the time beginning. that's why i said "change ID", so whenever the time comes, you guys could do that yourselves. i don't have access to the discord account obviously :P

2021-03-14 01:58 UTC, mjkzy commented
> Good job, but the TODOs need to be done ;)

I might try to mess with this but I lack knowledge and i’m still learning! :)

2021-03-14 04:26 UTC, mjkzy commented on src/client/component/discord.cpp
> +				/*discord_presence.partySize = game::mp::cgArray->snap != nullptr
couldn't get around to doing this because I think I need to reverse AW and I don't know how to really do that or have IDA so I just disabled party related info as a whole (for now, atleast)

2021-03-21 11:12 UTC, momo5502 commented
I'm closing this for now, cause of build system issues.
This will have to be redone anyways, as the presence id must be created by us.

2021-03-21 11:13 UTC, momo5502 commented
This might be reopened/reused at later times

2021-04-05 12:01 UTC, momo5502 approved these changes

2021-04-05 12:02 UTC, merged