Use builtin lua compiler
XLabsProject/s1x-client pull request #376
Opened 2022-04-29 22:25 UTC by fedddddd

Recently found out that the game already has it built-in

2022-05-03 06:56 UTC, momo5502 requested changes

2022-05-03 06:56 UTC, momo5502 commented on src/client/component/logger.cpp
> +			utils::hook::jump(0x140701A1C, print);
A comment would be nice

2022-05-03 06:56 UTC, momo5502 commented on src/client/component/ui_scripting.hpp
> +	}
Why the index sequence? Can't you just forward the arguments as universal references?

2022-05-03 06:56 UTC, momo5502 commented on src/client/game/ui_scripting/script_value.cpp
> +	script_value::script_value(const char* value, unsigned int len)
size_t len?

2022-05-03 09:48 UTC, fedddddd commented on src/client/component/ui_scripting.hpp
> +	}
I use it so I can unpack `function_arguments`, which is pretty much a vector

2022-06-06 16:02 UTC, fedddddd commented on src/client/component/ui_scripting.hpp
> +	}
The purpose of `wrap_function` is to transform any `std::function` into an `std::function` that can be called from [`function_arguments`](https://github.com/fedddddd/s1x-client/blob/lui-scripting-/src/client/game/ui_scripting/script_value.hpp#L242) which stores the arguments from the lua stack, I need the index sequence so I can unpack the values from the stack and convert them to the proper type. I can't std::forward `Args...` because those are just argument types.

2022-06-06 17:37 UTC, momo5502 commented on src/client/component/ui_scripting.hpp
> +	}
You are right, as you are iterating a vector-like container, my comment is absolutly bullshit and doesn't make sense.

2022-06-06 17:37 UTC, momo5502 approved these changes

2022-06-06 17:37 UTC, merged