Add commercial Messages
XLabsProject/s1x-client pull request #432
Opened 2022-09-13 14:48 UTC by hosseinpourziyaie

port of my demonware investigation on H1 MarketingComms. However here done with different method by directly hooking marketing_getMessage(lui's contact in engine)

2022-09-13 15:58 UTC, diamante0018 commented
What does this do for s1x?

2022-09-13 16:30 UTC, hosseinpourziyaie commented
> What does this do for s1x? I mean we already have a custom message of the day...

its a panel on online menu and its data is fetched from one of demonware lobby tasks in original game. unlike motd it stays in menu. also can have interactable popup window 
![2022-09-13 07 23 47](https://user-images.githubusercontent.com/22142481/189955894-1119bdce-b0b5-4472-972b-8151f45861d4.jpg)

2022-09-13 16:34 UTC, diamante0018 requested changes
I see,
Please address the review.
You may wait for momo5002 to see if he wants this to be merged.

2022-09-13 16:34 UTC, diamante0018 commented on src/client/component/motd.cpp
> +		std::string marketing_featuredMsg;
snake case

2022-09-13 16:34 UTC, diamante0018 commented on src/client/component/motd.cpp
> +	bool marketing_getMessage_stub(int controllerIndex, int locationID, char* messageText, int messageTextLength)
snake case function and parameter names

2022-09-13 16:34 UTC, diamante0018 commented on src/client/component/motd.cpp
> +	utils::hook::detour marketing_getMessage_hook;
snake case

2022-09-13 16:34 UTC, diamante0018 commented on src/client/component/motd.cpp
> +#define Feautured_Template "{\"content_short\": \"Welcome to S1X\", \"image\": \"icon_pl_cat_exo\", \"content_long\": \"<body>After Years of gaining experience towards reverse engineering, xLabs deve
Macros should be all caps

2022-09-14 07:03 UTC, momo5502 commented on src/client/component/motd.cpp
> +#define Feautured_Template "{\"content_short\": \"Welcome to S1X\", \"image\": \"icon_pl_cat_exo\", \"content_long\": \"<body>After Years of gaining experience towards reverse engineering, xLabs deve
no need for a macro here at all

2022-09-14 07:05 UTC, momo5502 commented on src/client/component/motd.cpp
> +#define FEAUTURED_TEMPLATE "{\"content_short\": \"Welcome to S1X\", \"image\": \"icon_pl_cat_exo\", \"content_long\": \"<body>After Years of gaining experience towards reverse engineering, xLabs deve
Despite all the typos and grammar issues, the text is a bit weird. Maybe just pasting the MOTD text would be better?

2022-09-14 07:05 UTC, momo5502 commented on src/client/component/motd.cpp
> +#define FEAUTURED_TEMPLATE "{\"content_short\": \"Welcome to S1X\", \"image\": \"icon_pl_cat_exo\", \"content_long\": \"<body>After Years of gaining experience towards reverse engineering, xLabs deve
Ah nvm, the goal is to fetch this from the server. That seems good to me.

2022-09-14 07:07 UTC, momo5502 commented on src/client/component/motd.cpp
> +
Remove this and the macro and I'll add the json to the server. Other than that it looks good

2022-09-14 07:07 UTC, momo5502 requested changes
Remove the preview and I'll add the json when I have time, then it looks good to me

2022-09-14 12:20 UTC, hosseinpourziyaie commented
> 

cutted out. i had included that as a template so you could have basic idea of what is needed to be on server as json objects and data

2022-09-14 12:45 UTC, diamante0018 requested changes

2022-09-14 12:45 UTC, diamante0018 commented on src/client/component/motd.cpp
> +		std::string marketing_featured_msg_str;
the name can be just `marketing_featured_msg` we can see it's a string from the std::string declaration already :)

2022-09-14 12:45 UTC, diamante0018 commented on src/client/component/motd.cpp
> +	bool marketing_get_message_stub(int controllerIndex, int locationID, char* messageText, int messageTextLength)
snake case parameter names too

2022-09-14 12:45 UTC, diamante0018 commented on src/client/component/motd.cpp
> +		strncpy(messageText, marketing_featured_msg_str.data(), messageTextLength);
This is unsafe as it can overwrite the last character (`\0`)
You should use strncpy_s https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strncpy-s-strncpy-s-l-wcsncpy-s-wcsncpy-s-l-mbsncpy-s-mbsncpy-s-l?view=msvc-170 or ensure the null terminating character is always written

2022-09-14 16:18 UTC, mjkzy commented on src/client/component/motd.cpp
> +	bool marketing_get_message_stub(int controllerIndex, int locationID, char* messageText, int messageTextLength)
and, if you want to, you can call long names like messageTextLength "text_len" or just "length".

2022-09-20 07:56 UTC, hosseinpourziyaie commented on src/client/component/motd.cpp
> +	bool marketing_get_message_stub(int controllerIndex, int locationID, char* messageText, int messageTextLength)
i named parameters in way look like original game engine's naming standards

2022-09-20 08:02 UTC, diamante0018 commented on src/client/component/motd.cpp
> +	bool marketing_get_message_stub(int controllerIndex, int locationID, char* messageText, int messageTextLength)
We don't want that. Please use snake case.

2022-09-20 08:33 UTC, hosseinpourziyaie commented on src/client/component/motd.cpp
> +		strncpy(messageText, marketing_featured_msg_str.data(), messageTextLength);
code updated

2022-10-15 14:07 UTC, diamante0018 requested changes

2022-10-15 14:07 UTC, diamante0018 commented on src/client/component/motd.cpp
>  				{
Please restore the original indentation of std::thread lambda function.
Remove the extra tabs that visual studio adds for you
It should be:
`
std::thread([]()
{
...
});
`
Thanks

2022-11-06 18:20 UTC, momo5502 commented
https://github.com/XLabsProject/s1x-client/pull/522

2022-11-06 18:20 UTC, closed without merging