Feature/quaK
XLabsProject/s1x-client pull request #81
Opened 2021-04-15 14:12 UTC by Joelrau

2021-04-15 15:13 UTC, momo5502 requested changes
Small comments

2021-04-15 15:13 UTC, momo5502 commented on src/client/component/logfile.cpp
> +				hidden = message[1] == '/';
why 1 here?

2021-04-15 15:13 UTC, momo5502 commented on src/client/component/network.cpp
> +					console::info(message.data());
nah, it needs the newline, console::info/error/warn, don't add these automatically anymore, i wanted it to behave just like printf

2021-04-15 15:13 UTC, momo5502 commented on src/client/component/network.cpp
> +					console::info(message.data());
nvm, i see what you did there, it's ofc totally fine. ignore my comment :)

2021-04-15 15:13 UTC, momo5502 commented on src/client/component/rcon.cpp
> +		bool is_redirecting_ = false;
I would have made this volatile, but considering volatile is deprecated now ¯\_(ツ)_/¯

2021-04-15 15:13 UTC, momo5502 commented on src/client/component/rcon.cpp
> +		std::lock_guard<std::recursive_mutex> $(redirect_lock);
Here, what you can do is add a if(!is_redirecting_) return false; in front. That way, if redirecting is not enabled, you're not unnecessarily acquiring the mutex. And when it is, you acquire the mutex and do the stuff below as it is

2021-04-15 15:43 UTC, momo5502 approved these changes

2021-04-15 15:43 UTC, merged

2022-10-31 20:02 UTC, diamante0018 commented on src/client/component/network.cpp
> +					console::info(message.data());
Oops